---
- name: Base bamboo service
  hosts: base
  become: yes
  roles:
    - { role: nodejs, tags: nodejs }
    - { role: counter-panda, tags: counter-panda }
    - { role: gify-panda, tags: gify-panda } 
    
